image: ${SYSREPO_CICD_IMAGE}

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - generate
  - build

generate:
  stage: generate

  script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - mkdir generated
    - mkdir generated/ietf-system
    - echo $LD_LIBRARY_PATH
    - python3 src/sysrepo-plugin-generator.py -d yang -m ietf-system -o generated/ietf-system -M ietf-system
  
  artifacts:
    paths:
      - generated/

build:
  stage: build

  script:
    # build system plugin
    - mkdir generated/ietf-system/build && cd generated/ietf-system/build
    - cmake -DSYSTEMD_IFINDEX=1 -DCMAKE_C_COMPILER=clang -S .. -B . && make -j
  
  artifacts:
    paths:
      - generated/ietf-system/build
