image: ${SYSREPO_CICD_IMAGE}

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - generate
  - build

generate:
  stage: generate

  script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - mkdir generated
    - mkdir generated/ietf-system
    - python src/sysrepo-plugin-generator.py -d yang -o gen/ietf-system --lang="C" -c config/ietf-system.toml
  
  artifacts:
    paths:
      - generated/

build:
  stage: build

  script:
    # build system plugin
    - mkdir generated/ietf-system/build && cd generated/ietf-system/build
    - cmake -DSYSTEMD_IFINDEX=1 -DCMAKE_C_COMPILER=clang -S .. -B . && make -j
  
  artifacts:
    paths:
      - generated/ietf-system/build
