[generator]
prefix = "interfaces"

[yang.modules]
main = "ietf-interfaces"
other = ["ietf-ip", "ietf-if-extensions", "ietf-if-vlan-encapsulation", "ieee802-dot1q-bridge"]
features = ["sub-interfaces"]

[yang.types]
identityref = "char *"

[yang.prefix]
interface = "interface"
# statistics = "statistics"
# address = "addr"
# neighbor = "neigh"
# ipv4 = "ipv4"
# ipv6 = "ipv6"
