[generator]
prefix = "ietf_sys"

[yang.modules]
main = "ietf-system"
other = []

[yang.types]
identityref = "char *"

[yang.prefix]
ntp = "ntp"
dns_resolver = "dns"
radius = "radius"
authentication = "auth"
clock = "clock"
platform = "platform"
system_state = "state"