[generator]
name = "ietf-system"

[yang.modules]
main = [
    {
        name = "ietf-system", 
        prefix = "ietf-system",
        skip_prefix_mode = "root",
        disable = true
    }
]
other = ["ietf-inet-types", "ietf-netconf-acm", "iana-crypt-hash"]

[yang.modules.features]
"ietf-system" = []

[yang.types]
