[generator]
prefix = "ietf_ifc"

[yang.modules]
main = "ietf-interfaces"
other = ["ietf-ip"]

[yang.types]
identityref = "char *"

[yang.prefix]
statistics = "stats"
address = "addr"
neighbor = "neigh"
ipv4 = "ipv4"
ipv6 = "ipv6"
